;/*FB_PKG_DELIM*/

__d("LSIssueNewTaskWithExtraOperationsAndGetTaskID",["LSIssueNewTaskAndGetTaskID","LSMailboxTaskCompletionApiOnTaskInsertion"],(function(a,b,c,d,e,f){function a(){var a=arguments,c=a[a.length-1],d=[],e=[];return c.sequence([function(f){return c.sequence([function(e){return c.storedProcedure(b("LSIssueNewTaskAndGetTaskID"),a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8],a[9],a[11]).then(function(a){return a=a,d[0]=a[0],a})},function(a){return c.storedProcedure(b("LSMailboxTaskCompletionApiOnTaskInsertion"),d[0])},function(a){return e[0]=d[0]}])},function(a){return c.resolve(e)}])}a.__sproc_name__="LSCoreIssueNewTaskWithExtraOperationsAndGetTaskIDStoredProcedure";a.__tables__=[];e.exports=a}),null);
__d("LSPlatformWaitForTaskCompletion",["I64","Promise","asyncToGeneratorRuntime","emptyFunction","err","justknobx","promiseDone","uuidv4"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=["acs_sync"];function a(a,b,c,d){return k.apply(this,arguments)}function k(){k=b("asyncToGeneratorRuntime").asyncToGenerator(function*(a,e,g,k){var l=new Set(),m=[],n=0,o=!0,p,q,r=new(i||(i=b("Promise")))(function(a,b){p=a,q=b}),s=c("uuidv4")(),t=!0,u=(yield a.runInTransaction(function(){var i=b("asyncToGeneratorRuntime").asyncToGenerator(function*(i){yield i.mailbox_task_completion_notification_context.add({notificationName:g,notificationScopeKey:s});var r=a.tables.pending_tasks.subscribe(function(a,b){a=(h||(h=d("I64"))).to_string(a[0]);if(b.operation==="add"||b.operation==="put"){var e=b.value;if(c("justknobx")._("2903")&&j.some(function(a){return e.queueName.startsWith(a)}))return;if(k!=null&&e.queueName!==k)return;l.add(a)}else l["delete"](a)}),v=c("emptyFunction"),w=a.tables.mailbox_task_completion_api_tasks.subscribe(function(a,b){if(b.operation==="add"||b.operation==="put"&&b.value.notificationScopeKey===s){a=(h||(h=d("I64"))).to_string(b.value.taskId);l["delete"](a);b=b.value.success;b==null?t&&(m.push(a),n+=1):(o=b&&o,n-=1)}});v=a.subscribeToCommit(function(){n===0&&l.size===0&&(w(),r(),v(),c("promiseDone")(a.runInTransaction(function(){var a=b("asyncToGeneratorRuntime").asyncToGenerator(function*(a){for(var b of m)yield a.mailbox_task_completion_api_tasks["delete"]((h||(h=d("I64"))).of_string(b))});return function(b){return a.apply(this,arguments)}}(),"readwrite","background",void 0,f.id+":150")),o?p(u):q(c("err")("Not all tasks for "+g+" succeeded")))});try{var x=(yield e(i));yield i.mailbox_task_completion_notification_context["delete"](s);return x}catch(a){v();w();r();throw a}});return function(a){return i.apply(this,arguments)}}(),"readwrite",void 0,void 0,f.id+":66"));t=!1;return r});return k.apply(this,arguments)}g["default"]=a}),98);
__d("LSPredefineTraceForTask",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1],c=[],d=[];return b.sequence([function(d){return b.sequence([function(d){return c[0]=b.i64.of_float(Date.now()),b.forEach(b.db.table(2).fetch([[[a[1]]]]),function(b){var d=b.update;b.item;return d({dataTraceId:a[0],initTraceTimestampMs:c[0]})})},function(d){return b.db.table(153).add({traceId:a[0],initTimestampMs:c[0],foregroundTimestampMs:b.i64.cast([0,0]),traceType:b.i64.cast([0,1]),shouldFlush:!1,contextOne:a[2],contextTwo:b.i64.to_string(a[1]),predefinedId:a[3]})}])},function(a){return b.resolve(d)}])}a.__sproc_name__="LSDataTracePredefineTraceForTaskStoredProcedure";a.__tables__=["pending_tasks","data_trace_meta"];e.exports=a}),null);
__d("Lexical",["cr:370"],(function(a,b,c,d,e,f){e.exports=b("cr:370")}),null);
__d("LexicalComposerContext",["cr:509"],(function(a,b,c,d,e,f){e.exports=b("cr:509")}),null);
__d("LexicalText",["cr:2181"],(function(a,b,c,d,e,f){e.exports=b("cr:2181")}),null);
__d("LexicalUtils",["cr:2774"],(function(a,b,c,d,e,f){e.exports=b("cr:2774")}),null);
__d("isThreadLevelCutoverEnabled",["qex"],(function(a,b,c,d,e,f,g){"use strict";function a(){return c("qex")._("564")===!0}g["default"]=a}),98);
__d("MLCInstrumentationCommands",["Lexical"],(function(a,b,c,d,e,f,g){"use strict";b=(a=d("Lexical")).createCommand();c=a.createCommand();e=a.createCommand();f=a.createCommand();g.COMMIT_COMMAND=b;g.INTERACTION_INSTRUMENTATION_READY=c;g.DOCUMENT_COMMAND=e;g.PLUGIN_EVENT_COMMAND=f}),98);
__d("MWLSContactTypeExactUtils",["I64","LSContactTypeExact","LSIntEnum"],(function(a,b,c,d,e,f,g){"use strict";var h,i;function a(a){if((h||(h=d("I64"))).equal(a,(i||(i=d("LSIntEnum"))).ofNumber(c("LSContactTypeExact").IG_USER))||(h||(h=d("I64"))).equal(a,(i||(i=d("LSIntEnum"))).ofNumber(c("LSContactTypeExact").IG_BUSINESS_USER)))return!0;else return(h||(h=d("I64"))).equal(a,(i||(i=d("LSIntEnum"))).ofNumber(c("LSContactTypeExact").IG_CREATOR_USER))}g.isIgContact=a}),98);
__d("coerceMessagingThreadTypeToLSThreadType",["LSIntEnum"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a){return(h||(h=d("LSIntEnum"))).unwrapIntEnum(a)}g["default"]=a}),98);
__d("useDebouncedComet",["CometDebounce","react","useStable"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useEffect,j=b.useLayoutEffect,k=b.useRef;function a(a,b){var d=k(a);j(function(){d.current=a},[a]);var e=c("useStable")(function(){return c("CometDebounce")(function(){d.current.apply(void 0,arguments)},b)});i(function(){return function(){e.reset()}},[]);return e}g["default"]=a}),98);